# Generated by Django 4.0 on 2022-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenomEmploye', models.CharField(max_length=200, null=True)),
                ('nomEmploye', models.CharField(max_length=200, null=True)),
                ('emailEmploye', models.CharField(max_length=200, null=True)),
                ('telEmploye', models.CharField(max_length=200, null=True)),
                ('mdpEmploye', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
