# Generated by Django 4.0 on 2022-04-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('prestations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='users.newuser'),
        ),
    ]
