# Generated by Django 4.0 on 2022-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenomClient', models.CharField(max_length=200, null=True)),
                ('nomClient', models.CharField(max_length=200, null=True)),
                ('ageClient', models.IntegerField(null=True)),
                ('emailClient', models.CharField(max_length=200, null=True)),
                ('telClient', models.CharField(max_length=15, null=True)),
                ('rueClient', models.CharField(max_length=60, null=True)),
                ('complementAdresseClient', models.CharField(max_length=100, null=True)),
                ('villeClient', models.CharField(max_length=200, null=True)),
                ('cpClient', models.CharField(max_length=8, null=True)),
                ('qr_code', models.ImageField(null=True, upload_to='qr_codes')),
                ('codeClient', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
